In [1]:
import numpy as np


# NUMPY

## Numpy is multidimentional array processing open source package, which is suitable for mathematical operations on arrays and linear algebra.

## Numpy array is faster than python list, reason is :
    1. Numpy uses fix types and less memory (less memory = faster read)
        * Numpy by default uses int32 (4 bytes) for saving integers (the size is customizable)
        * List uses a builtin int type which consists of 4 part (28 bytes)
            . Size (4 bytes)
            . Reference count (8 bytes)
            . Object type (8 bytes)
            . Object value (8 bytes)
            
    2. Every time we iterate over a numpy array python interpreter doesn't need type checking each time BUT in list for each item's type it should be checked

    3. Numpy uses continues memory locations.
        . In list, we have a list of references to diferent memory locations
        . But a numpy array is just a reference to the first item and the others are next to each other.
## Numpy array supports item wise methematical operations like np.array([1, 2]) * np.array([2, 3]) 


In [12]:
np.array([2, 3]) * np.array([1, 2])

array([2, 6])

### EXP1

In [25]:
int_arr = np.array([
    [
        [1,2,3,4],
        [2,3,4,5]
    ],
    [
        [4,5,6,7],
        [4,3,6,7]
    ],
    [
        [1,3,6,7],
        [3,4,4,4]
    ]
], dtype='int16') # 16 bits or 2 bytes

In [26]:
int_arr.ndim


3

In [27]:
int_arr.shape


(3, 2, 4)

In [28]:
int_arr.dtype


dtype('int16')

In [29]:
int_arr.itemsize # bytes


2

In [30]:
int_arr.size * int_arr.itemsize 


48

In [31]:
int_arr.nbytes


48

### EXP 2

In [33]:
float_arr = np.array([.5 , 1.1], dtype='float16')

In [40]:
print(
    f'\n dtype: %s' %float_arr.dtype,
    f'\n itemsize: %s' %float_arr.itemsize,
    f'\n numberOfItems * each_items_size: ', float_arr.size * float_arr.itemsize,
    f'\n bytes: %s' %float_arr.nbytes
)


 dtype: float16 
 itemsize: 2 
 numberOfItems * each_items_size:  4 
 bytes: 4


### EXP 3

In [41]:
d3_arr = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

In [42]:
d3_arr[0,1,2], d3_arr[1, 1, -2]

(6, 11)

In [43]:
d3_arr[1, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
d3_arr[1, :, 1:3:1]

array([[ 8,  9],
       [11, 12]])

# Manipulation

In [58]:
d3_arr[0, 0, 0] = 200
d3_arr

array([[[200,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [45]:
d3_arr[:, 1, 1] = [23, 48]
d3_arr[:, 1]

array([[ 4, 23,  6],
       [10, 48, 12]])

# Initialization

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((2, 3, 4, 5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [77]:
np.ones_like(d3_arr)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [76]:
np.zeros_like(d3_arr)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [72]:
np.full((2, 3), 88, dtype='float32')

array([[88., 88., 88.],
       [88., 88., 88.]], dtype=float32)

In [73]:
np.full_like(d3_arr, 6) # Uses d3_arr shape for creation

array([[[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]]])

In [74]:
np.full(d3_arr.shape, 99), # Just like above

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [79]:
np.random.rand(3, 2, 3)

array([[[0.37842133, 0.14719732, 0.76600629],
        [0.68430418, 0.20997209, 0.2064759 ]],

       [[0.74887576, 0.63289346, 0.30240857],
        [0.87122597, 0.35873257, 0.14165578]],

       [[0.29933213, 0.72108441, 0.99817502],
        [0.72153407, 0.3677108 , 0.25577488]]])

In [84]:
np.random.random_sample(size=d3_arr.shape)

array([[[0.61666973, 0.09296964, 0.22129899],
        [0.83953532, 0.11831485, 0.86286771]],

       [[0.83630782, 0.86549152, 0.84268963],
        [0.98139915, 0.95139306, 0.9910674 ]]])

In [117]:
np.random.randint(low=-4, high=7, size=(3,3))

array([[ 0, -4,  2],
       [-4, -3, -3],
       [ 2,  2,  1]])

In [118]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [128]:
arr_1 = np.array([[1, 2, 3]]) # THIS ARRAY IS 2_DIMENTIONAL
np.repeat(arr_1, 2, axis=0), np.repeat(arr_1, 2, axis=1)

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 2, 2, 3, 3]]))

## Copying a numpy array is a shallow copy ( Use copy.deepcopy if the array contains mutable items)

In [51]:
dict_arr = np.array([
    [{"a": "1"}, 1],
    [{"b": "2"}, 2]
])

import copy
# dict_arr2 = dict_arr.copy()
dict_arr2 = copy.deepcopy(dict_arr)

dict_arr2[1, 0]['b'] = '44444'
dict_arr2[1, 1] = 3

dict_arr2, dict_arr


(array([[{'a': '1'}, 1],
        [{'b': '44444'}, 3]], dtype=object),
 array([[{'a': '1'}, 1],
        [{'b': '2'}, 2]], dtype=object))

# Element wise mathematical operations
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [248]:
data_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

data_arr2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])



In [245]:
data_arr + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [246]:
np.sin(data_arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [249]:
data_arr + data_arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

# Linear Algebra
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
    . Determinant
    . Trace
    . Singular Vector Decomposition
    . Eigenvalues
    . Matrix Norm
    . Inverse
    . Etc...


In [99]:
sum(np.array([
        [1,2],
        [2,3]
    ])
)

array([3, 5])

In [53]:
a = np.ones((2, 3))
b = np.full((3,2), 5)

In [54]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

## np.linalg.det()

In [55]:
identity_arr = np.identity(5) 

In [71]:
np.linalg.det(identity_arr)

1.0

In [72]:
# creating a 2X2 Numpy matrix 
n_array = np.array([[50, 29], [30, 44]]) 

# Displaying the Matrix 
print("Numpy Matrix is:") 
print(n_array) 

# calculating the determinant of matrix 
det = np.linalg.det(n_array) 

print(f'\nDeterminant of given matrix is ({n_array[0][0]} * {n_array[1][1]}) - ({n_array[0][1]} * {n_array[1][0]}):') 
print(int(det)) 

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given matrix is (50 * 44) - (29 * 30):
1330


## np.dot()

In [81]:
f_arr = np.array(range(1,5))
s_arr = np.array(range(5,9))

np.dot(f_arr, s_arr) # like np.matmul() because they are 1D arrays.


70

In [87]:
f_arr = np.array([[1,2, 3], [2,3,4]])
s_arr = np.array([[4,5], [6,7], [4,5]])
f_arr, s_arr
np.dot(f_arr, s_arr)

array([[28, 34],
       [42, 51]])

## np.inner()

In [91]:
a = np.full(fill_value=2, shape=(3,3))
b= np.full(fill_value=3, shape=(3,3))
a, b

(array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]),
 array([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]))

In [93]:
a[:] * b[:] # should have same shape

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [101]:
# res[i, j]  = row[i] * col[j]
np.inner(a, b) # satr * sotoon be shart barabariye satrhaye matrix aval va sotoon haye matrix dovom


array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

# Statistics

In [114]:
stat_arr = np.array([
    [3, 5, 9],
    [2, 4, 11]
])

In [116]:
stat_arr.max(axis=1),  stat_arr.max()  # Take care of axis

(array([ 9, 11]), 11)

In [117]:
stat_arr.min(axis=0), stat_arr.min()  # Take care of axis

(array([2, 4, 9]), 2)

In [118]:
np.sum(stat_arr), np.sum(stat_arr, axis=0), np.sum(stat_arr, axis=1)

(34, array([ 5,  9, 20]), array([17, 17]))

# Array Organizing

In [120]:
org_arr = np.array([
    [3, 5, 9, 23],
    [2, 4, 11,  43]
])

In [121]:
np.reshape(org_arr, newshape=(2,2,2))

# -------------------------------------------------- 
 # np.reshape(org_arr, newshape=(2,2,3)) RAISES ERROR
# -------------------------------------------------- 

array([[[ 3,  5],
        [ 9, 23]],

       [[ 2,  4],
        [11, 43]]])

In [122]:


# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# External data source

In [127]:
data_from_file = np.genfromtxt('../resources/data.txt', delimiter=',').astype('int16')
print(data_from_file)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean masking & Advanced indexing

In [128]:
data_from_file[data_from_file > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [129]:
np.any(data_from_file > 50, axis=1)

array([ True,  True,  True])

In [130]:
np.all(data_from_file > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [298]:
data_from_file[(data_from_file > 50) & (data_from_file < 100)]

array([75, 75, 55, 78, 76, 88], dtype=int16)

![alternative text](../resources/question.png)

In [299]:
question_arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
]) 

In [301]:
question_arr[
    [0,1,2,3],
    [1,2,3,4]
]

array([ 2,  8, 14, 20])